FROM golang:1.12.7

# WORKDIR /go/src/app

RUN go get github.com/astaxie/beego
RUN go get github.com/google/uuid
RUN go get github.com/beego/bee
RUN go get github.com/astaxie/beego/toolbox
RUN go get github.com/go-sql-driver/mysql
RUN go get github.com/go-redis/redis

